[platformio]
default_envs = standalone_eeprom

[env:standalone_eeprom]
platform = atmelavr
board = megaatmega2560
framework = arduino

monitor_speed = 500000

build_flags =
    -Wall
    -Wextra
    -DSTANDALONE_EEPROM=1

[env:incircuit_ben_eater]
platform = atmelavr
board = megaatmega2560
framework = arduino

monitor_speed = 500000

build_flags =
    -Wall
    -Wextra
    -DSTANDALONE_EEPROM=0
